#!/bin/bash
#######
## Pre/Post-Processing example script
## Eric Pierce (epierce@usf.edu) 11/2/2012
##
## This script takes three parameters:
##   svnProcess ACTION ENVIRONMENT FILE
##
##  ACTION: either "pre" or "post" 
##      - "pre" ensures the JSON file in SVN matches the on in use
##      - "post" checks the updated JSON file into SVN
##
##  ENVIRONMENT: The CAS environment this JSON file is associated with.  
##  At USF we use multiple CAS instances and have dev/pre-prod/prod environments, 
##  so ours look like this:
##     LDAP authenticated                  Social network authenticated
##     Development/netid                   Development/social
##     PreProduction/netid                 PreProduction/social
##     Production/netid                    Production/social
##
##  FILE: JSON file that is being checked in
#########
LOCAL_REPO="$CASTOOL_HOME/svn/$2"
FILENAME=`basename $3`
JIRA_ISSUE='USFCAS-3'

case "$1" in

"pre")	echo "Starting Pre-Processing..."
	svn update $LOCAL_REPO

	if [ ! -e $LOCAL_REPO/$FILENAME ]; then
	echo "$LOCAL_REPO/$FILENAME does not exist!"
	exit 1
	fi

	diff -q $LOCAL_REPO/$FILENAME $3

	if [ $? == 1 ]; then
		echo "Current version of JSON file doesn't match latest version in SVN"
		exit 1
	fi

	;;
"post")	echo "Starting Post-Processing..."	
	cp $3 $LOCAL_REPO/$FILENAME
	json-to-csv --input $LOCAL_REPO/$FILENAME --output $LOCAL_REPO/$FILENAME.csv

	svn ci -m "$JIRA_ISSUE #comment Automatic commit from cas-json-tool" $LOCAL_REPO
			
	;;
esac